# Configuration for the services that are required to run an analysis of the
# data from riff edu mattermost.
# see https://www.metabase.com/docs/latest/operations-guide/running-metabase-on-docker.html
version: '3.6'
services:

  target-db:
    image: mysql:5.7
    container_name: mysql-business-analytics
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - target-db-data:/var/lib/mysql

  metabase:
    image: metabase/metabase:latest
    container_name: metabase-business-analytics
    environment:
      MB_DB_FILE: ./metabase-db/metabase.db
    ports:
      - '3000:3000'
    volumes:
      - ./metabase-db:/metabase-db
    depends_on:
      - target-db

volumes:
  target-db-data:
  metabase-db:
